#!/usr/bin/env python3
"""
Import species from the FishRadar catalog, enriched with Wikipedia/Wikidata
and FishBase, generating one profile .md file per species under
encyclopedia/data/fish/.

Sources combined (see docs/adr/0002-species-data-pipeline.md):
  - FishRadar data/species.json     -> species list, aliases, environment,
                                       seasonMonths, conservation status
  - Wikipedia REST page/summary     -> page title, lead extract, hero image,
                                       wikibase_item
  - Wikidata SPARQL (P171/P105)     -> class, order, family, genus
  - FishBase (parquet mirror)       -> physical, habitat, real distribution
                                       points (encyclopedia/fishbase.py)

Regeneration policy: hand-crafted profiles (no "generated by import_species.py"
comment) are normally never overwritten; pass --force to regenerate everything
through the same pipeline. A small JSON cache avoids re-hitting the external
APIs on rerun.
"""
import json
import re
import sys
import time
import urllib.request
import urllib.parse
from pathlib import Path

import yaml

sys.path.insert(0, str(Path(__file__).resolve().parent.parent))

from encyclopedia.fishbase import FishBase, build_fishbase_enrichment, build_biology, strip_citations

ROOT = Path(__file__).resolve().parent.parent
DATA_DIR = ROOT / "encyclopedia" / "data"
FISH_DIR = DATA_DIR / "fish"
OUT_DIR = ROOT / "encyclopedia" / "out"
CACHE = OUT_DIR / ".import-cache.json"

USER_AGENT = "FishpediaImporter/1.0 (fishing encyclopedia builder; contact: mattia@example.com)"

FISHRADAR_URL = ("https://raw.githubusercontent.com/linkanlabs-ctrl/"
                 "fishing-species-catalog/main/data/species.json")

RANK_FILTER = {
    "Q37517": "order",
    "Q35409": "family",
    "Q34740": "genus",
    "Q37528": "class",
}

CONSERVATION = {
    "cites-ii": "CITES-II",
    "no-retention": "NO-RETENTION",
    "permit-required": "PERMIT-REQUIRED",
    "vulnerable": "VU",
}

# Family fallback for species whose Wikidata family rank doesn't resolve
# (keyed by scientific name). Keeps taxonomy out of "Incertae sedis".
FAMILY_OVERRIDES = {
    "tinca tinca": "Tincidae",
    "colossoma macropomum": "Serrasalmidae",
    "gerres cinereus": "Gerreidae",
    "cyprinus rubrofuscus": "Cyprinidae",
    "isurus oxyrinchus": "Lamnidae",
}

# Scientific names that differ between the FishRadar catalog and the FishBase
# species/occurrence tables (keyed by catalog name -> FishBase name).
FISHBASE_ALIASES = {
    "salmo trutta trutta": "Salmo trutta",
    "chrysophrys auratus": "Pagrus auratus",
}

MONTH_NAMES = ["Jan", "Feb", "Mar", "Apr", "May", "Jun",
               "Jul", "Aug", "Sep", "Oct", "Nov", "Dec"]


def http_json(url, accept="application/json", timeout=45):
    req = urllib.request.Request(url, headers={
        "User-Agent": USER_AGENT,
        "Accept": accept,
    })
    with urllib.request.urlopen(req, timeout=timeout) as r:
        return json.load(r)


def wikipedia_summary(scientific):
    q = urllib.parse.quote(scientific.replace(" ", "_"))
    try:
        return http_json(f"https://en.wikipedia.org/api/rest_v1/page/summary/{q}")
    except Exception:
        return None


def wikibase_item_from_title(title):
    t = urllib.parse.quote(title.replace(" ", "_"))
    url = ("https://en.wikipedia.org/w/api.php?action=query&titles=" + t +
           "&prop=pageprops&ppprop=wikibase_item&format=json&formatversion=2&redirects=1")
    try:
        d = http_json(url)
        pages = d.get("query", {}).get("pages", [])
        if pages and "pageprops" in pages[0]:
            return pages[0]["pageprops"].get("wikibase_item")
    except Exception:
        pass
    return None


def wikidata_taxonomy(qid):
    query = f"""SELECT ?rank ?itemLabel WHERE {{
  wd:{qid} wdt:P171* ?ancestor .
  ?ancestor p:P105/ps:P105 ?rank .
  ?ancestor rdfs:label ?itemLabel FILTER(LANG(?itemLabel)='en')
  FILTER(?rank IN (wd:Q37517, wd:Q35409, wd:Q34740, wd:Q37528))
}}"""
    url = "https://query.wikidata.org/sparql?" + urllib.parse.urlencode({"query": query})
    try:
        d = http_json(url, accept="application/sparql-results+json", timeout=60)
    except Exception:
        return {}
    out = {}
    for b in d.get("results", {}).get("bindings", []):
        rank = b["rank"].get("value", "").split("/")[-1]
        role = RANK_FILTER.get(rank)
        name = b.get("itemLabel", {}).get("value")
        if role and name:
            out[role] = name
    return out


def load_fishradar():
    return http_json(FISHRADAR_URL, timeout=60)


def read_existing():
    """Map scientific name -> profile path for species already in data/fish."""
    existing = {}
    for md in FISH_DIR.rglob("*.md"):
        text = md.read_text(encoding="utf-8")
        if not text.startswith("---"):
            continue
        parts = text.split("---", 2)
        if len(parts) < 3:
            continue
        try:
            meta = yaml.safe_load(parts[1]) or {}
        except Exception:
            continue
        sci = (meta.get("taxonomy") or {}).get("scientific_name")
        if sci:
            existing[sci.lower()] = md
    return existing


def build_profile(species, summary, tax, fb):
    sci = species["scientific"].strip()
    common = (species["english"] or "").strip()
    slug = species["id"] or layout_slug(sci)

    if " " in sci:
        genus, species_epithet = sci.split(" ", 1)
    else:
        genus, species_epithet = sci, ""

    water = species["environment"]
    season = species.get("seasonMonths") or []

    family = FAMILY_OVERRIDES.get(sci.lower()) or tax.get("family") or "Incertae sedis"
    # Non-fish (cephalopod) families in the catalog: correct the class.
    CEPHALOPOD_FAMILIES = {"Octopodidae", "Sepiidae", "Loliginidae", "Sepiolidae"}
    fish_class = "Cephalopoda" if family in CEPHALOPOD_FAMILIES else (tax.get("class") or "Actinopterygii")
    conservation = CONSERVATION.get(species.get("conservationStatus"), "LC")

    # FishBase enrichment (physical, habitat, biology, distribution points)
    # + Comments for the v2 Behavior prose section.
    fbname = FISHBASE_ALIASES.get(sci.lower(), sci)
    fb_enc = build_fishbase_enrichment(fb, fbname)
    spec_code = (fb.species_row(fbname) or {}).get("SpecCode")
    biology = build_biology(fb, spec_code)
    comments = fb.species_comments(fbname)
    behavior_text = build_behavior_text(comments)

    water_types = (fb_enc["habitat"].get("water_types")
                   or (["saltwater"] if water == "saltwater" else ["freshwater"]))
    habitat = dict(fb_enc["habitat"])
    habitat["water_types"] = water_types

    distribution = {"native": True}
    points = fb_enc["points"]
    if points:
        # Real observation/museum records => meaningful density scatter.
        distribution["points"] = [[round(lat, 3), round(lng, 3)] for lat, lng in points]
        distribution["source"] = "FishBase occurrence records"
    else:
        # No FishBase records (non-fish, or data gap): omit the map rather than
        # render a meaningless two-point band.
        distribution["points"] = []

    # v2 `facts` block: relocate the three lifecycle/phenology numbers from
    # their v1 homes (`physical.lifespan_years`, `biology.age_maturity`,
    # `angling.season_months`) into a single top-level block.
    physical = dict(fb_enc["physical"])
    facts = {}
    if "lifespan_years" in physical:
        facts["lifespan_years"] = physical.pop("lifespan_years")
    if "age_maturity" in biology:
        facts["age_maturity"] = biology.pop("age_maturity")
    if season:
        facts["season_months"] = season

    meta = {
        "id": slug,
        "slug": slug,
        "taxonomy": {
            "class": fish_class,
            "order": tax.get("order") or "",
            "family": family,
            "genus": genus,
            "species": species_epithet,
            "scientific_name": sci,
            "common_name": common,
            "aliases": species.get("aliases") or [],
        },
        "sources": {
            "fishbase_id": (fb.species_row(fbname) or {}).get("SpecCode"),
            "fishradar_id": slug,
            "wikidata_id": summary.get("wikibase_item") if summary else None,
        },
        "physical": physical,
        "habitat": habitat,
        "biology": biology,
        "distribution": distribution,
        "conservation": {"status": conservation},
    }
    if facts:
        meta["facts"] = facts
    if behavior_text:
        meta["behavior"] = behavior_text

    extract = (summary or {}).get("extract") or ""
    meta["description"] = extract.strip()
    body = build_body(common, sci, extract, biology)

    if summary and summary.get("originalimage"):
        image_url = summary["originalimage"]["source"].split("?")[0]
        page = (summary.get("content_urls") or {}).get("desktop", {}).get("page")
        meta["image"] = {
            "url": image_url,
            "alt": f"{common} ({sci})",
            "credit": f"Wikipedia — {summary.get('title', '')}",
            "credit_url": page,
        }

    frontmatter = yaml.safe_dump(meta, sort_keys=False, allow_unicode=True, width=100)
    text = "---\n" + frontmatter + "---\n\n" + body.strip() + "\n"
    text += "\n<!-- generated by import_species.py from FishRadar + Wikipedia/Wikidata + FishBase -->\n"
    return text


def months_list(months):
    names = ", ".join(MONTH_NAMES[m - 1] for m in sorted(months) if 1 <= m <= 12)
    return names or "year-round"


# --- Behavior filter (T12 resolution) ----------------------------------------

# Keep-keyword groups: a sentence matches if it contains any of these words.
# Each entry is a tuple of (label, regex). A sentence is "behavioral" if any
# of the six group regexes matches.
_BEHAVIOR_KEEP_GROUPS = {
    "temporal":     r"\b(nocturnal|diurnal|crepuscular|dawn|dusk|night\b|daytime)\b",
    "position":     r"\b(benthic|demersal|pelagic|benthopelagic|bottom|water column|surface|midwater)\b",
    "movement":     r"\b(migrat|school|shoal|solitary|territorial|wandering|sedentary)\b",
    "foraging":     r"\b(predator|prey|forag|hunt|ambush|carnivore|herbivore|planktivore|opportunistic)\b",
    "ontogeny":     r"\b(larvae|juvenile|adults?\b|ontogen|ontogenetic)\b",
    "reproduction": r"\b(spawn|spawning|nest|eggs|guard|parental)\b",
}
_BEHAVIOR_KEEP_RE = re.compile("|".join(_BEHAVIOR_KEEP_GROUPS.values()), re.IGNORECASE)

# Drop-keyword patterns: even if a sentence has a keep-keyword, drop it if
# any of these match. The sentence is actually a habitat / diet / age / length
# / human-use / conservation / parasites fact that already lives elsewhere.
_BEHAVIOR_DROP_PARTS = [
    r"\binhabit(?:s|ed|ing)?\b",
    r"\bfound in\b",
    r"\blives? in\b",
    r"\boccurs? in\b",
    r"\bendemic to\b",
    r"\bfeeds? (mainly )?on\b",
    r"\bdiets? of\b",
    r"\bpreys? on\b",
    r"\battain(?:s|ed|ing)? (first )?sexual maturity\b",
    r"\bsexual maturity\b",
    r"\bmaximum (?:length|weight|recorded)\b",
    r"\brecorded maxima\b",
    r"\bmaximum length of\b",
    r"\bmaximum weight of\b",
    r"\bpopularly fished\b",
    r"\bcommercially\b",
    r"\bgame fish\b",
    r"\butilized\b",
    r"\bmarketed\b",
    r"\beat(?:en|ing)\b",
    r"\battracts? no\b",
    r"\bharmless\b",
    r"\bdangerous\b",
    r"\blocally threatened\b",
    r"\blocally impacted\b",
    r"\bthreatened due\b",
    r"\bparasite\b",
    r"\bintermediate host\b",
]
_BEHAVIOR_DROP_RE = re.compile("|".join(_BEHAVIOR_DROP_PARTS), re.IGNORECASE)


def _behavior_split_sentences(text):
    """Split on . ! ? followed by whitespace, but not inside parentheses."""
    out, buf, depth = [], [], 0
    for ch in text:
        if ch == "(":
            depth += 1
            buf.append(ch)
        elif ch == ")":
            depth -= 1
            buf.append(ch)
        elif ch in ".!?" and depth == 0:
            buf.append(ch)
            s = "".join(buf).strip()
            if s:
                out.append(s)
            buf = []
        else:
            buf.append(ch)
    tail = "".join(buf).strip()
    if tail:
        out.append(tail)
    return out


def build_behavior_text(comments):
    """Sentence-filter the FishBase `species.Comments` paragraph.

    Returns the joined kept sentences (citation-stripped), or "" if no
    sentence passes the keep/drop filter. Locked by issue #12.
    """
    if not comments:
        return ""
    text = strip_citations(comments)
    kept = []
    for s in _behavior_split_sentences(text):
        s = s.strip()
        if not s:
            continue
        if _BEHAVIOR_KEEP_RE.search(s) and not _BEHAVIOR_DROP_RE.search(s):
            kept.append(s)
    return " ".join(kept).strip()


def build_body(common, sci, extract, biology):
    """Generate the prose portion of a profile markdown body.

    Sections are ordered to match the page anatomy; the Distribution block and
    fact-driven sections (Size/Weight/Age/Seasonality/Conservation) are
    rendered from frontmatter by the generator, so only Description and Biology
    carry prose here. Empty sections are omitted entirely.
    """
    lines = []
    if extract:
        lines += ["## Description", extract.strip(), ""]
    if biology:
        bio = build_biology_prose(common, biology)
        if bio:
            lines += ["## Biology", *bio, ""]
    return "\n".join(lines).strip()


def build_biology_prose(common, biology):
    """Merge FishBase biology into prose paragraphs for the Biology section."""
    paras = []
    repro = biology.get("reproduction")
    if repro:
        paras.append(repro)

    facts = []
    months = biology.get("spawning_months")
    if months:
        facts.append(f"Spawning occurs mainly in {months_list(months)}.")
    fec = biology.get("fecundity")
    if fec:
        facts.append(f"Fecundity ranges from {fec}.")
    if facts:
        paras.append(" ".join(facts))

    diet = biology.get("diet")
    if diet:
        paras.append(f"Its diet consists mainly of {join_list(diet)}.")
    predators = biology.get("predators")
    if predators:
        paras.append(f"It may be targeted by predators such as {join_list(predators, sci=True)}.")
    return paras


def join_list(items, sci=False):
    if not items:
        return ""
    if len(items) == 1:
        return items[0] if sci else items[0].lower()
    head = ", ".join(items[:-1])
    last = items[-1] if sci else items[-1].lower()
    return f"{head} and {last}"


def layout_slug(scientific):
    return scientific.replace(" ", "-").lower()


def main(force=False):
    FISH_DIR.mkdir(parents=True, exist_ok=True)

    species_list = load_fishradar()
    existing = read_existing()
    print(f"FishRadar catalog: {len(species_list)} species; existing profiles: {len(existing)}\n")

    fb = FishBase()

    cache = {}
    if CACHE.exists():
        try:
            cache = json.loads(CACHE.read_text(encoding="utf-8"))
        except Exception:
            cache = {}

    written = skipped = 0
    for sp in species_list:
        sci = (sp.get("scientific") or "").strip()
        if not sci:
            skipped += 1
            continue
        key = sci.lower()

        # Locate the profile path. Match by scientific name via frontmatter.
        # Used to detect hand-crafted profiles (never overwritten) — but the
        # write target is always the entry's own slug path, since the catalog
        # can list two entries under one scientific name (e.g. Atlantic vs
        # Pacific forms of the same species).
        existing_path = existing.get(key)
        if not force and existing_path is not None:
            marker = existing_path.read_text(encoding="utf-8")
            if "generated by import_species.py" not in marker:
                print(f"  - skip (hand-crafted): {sci}")
                skipped += 1
                continue

        info = cache.get(key, {})
        if not info:
            summary = wikipedia_summary(sci)
            qid = wikibase_item_from_title(summary.get("title", "")) if summary else None
            tax = wikidata_taxonomy(qid) if qid else {}
            info = {"summary": summary, "qid": qid, "tax": tax}
            cache[key] = info
            CACHE.parent.mkdir(parents=True, exist_ok=True)
            CACHE.write_text(json.dumps(cache, indent=2), encoding="utf-8")
            time.sleep(0.35)

        if not info["summary"]:
            print(f"  ✗ no wikipedia page: {sci}")
            skipped += 1
            continue

        # Directory (family/genus) must match the frontmatter exactly:
        # genus from the scientific name's first word, family from Wikidata,
        # both kebab-cased for the filesystem (validator computes the same way).
        fam_override = FAMILY_OVERRIDES.get(key)
        family = (fam_override or info["tax"].get("family") or "incertae sedis").lower().replace(" ", "-")
        genus = (sci.split(" ")[0] if " " in sci else "unknown").lower().replace(" ", "-")
        gen_dir = FISH_DIR / family / genus
        gen_dir.mkdir(parents=True, exist_ok=True)
        slug = sp.get("id") or layout_slug(sci)
        out_file = gen_dir / f"{slug}.md"

        profile = build_profile(sp, info["summary"], info["tax"], fb)
        out_file.write_text(profile, encoding="utf-8")
        print(f"  ✓ {sci} -> {out_file.relative_to(ROOT)}")
        written += 1

    print(f"\nDone — {written} written, {skipped} skipped")
    print("FishBase cache:", fb.table_paths())


if __name__ == "__main__":
    main(force="--force" in sys.argv)
